# Generated by Django 5.0 on 2023-12-30 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='price',
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='maps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='menu'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FoodJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='FoodJournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cafeteria_images')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafeteria.foodjournalentry')),
            ],
        ),
    ]
