# Generated by Django 5.0 on 2023-12-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_remove_cafeteria_date_remove_cafeteria_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='maps',
            field=models.URLField(blank=True, null=True),
        ),
    ]
